"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)


# With DEBUG=False the permissive defaults are gone: Django refuses every request
# whose Host header isn't listed here, and rejects POSTs whose Origin isn't
# trusted. Both are comma-separated in the environment so the container can be
# pointed at a new hostname without a rebuild.
#
# `localhost` and `127.0.0.1` are not interchangeable to Django — it matches the
# Host header as a literal string — so both are in the default.
ALLOWED_HOSTS = [
    h.strip()
    for h in config("ALLOWED_HOSTS", default="localhost,127.0.0.1").split(",")
    if h.strip()
]

# Must include the scheme, unlike ALLOWED_HOSTS. These are the origins the admin
# login and the DRF browsable API are allowed to be POSTed from; behind nginx the
# browser's origin is the *proxy's* port, not the backend's.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in config(
        "CSRF_TRUSTED_ORIGINS",
        default="http://localhost:8080,http://127.0.0.1:8080",
    ).split(",")
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    # Ships the Swagger UI JS/CSS as a Python package instead of loading it from
    # unpkg.com at page load. Without it /api/docs/ is a blank page whenever the
    # room's wifi is down — which is exactly when it gets opened.
    "drf_spectacular_sidecar",
    "corsheaders",
    "apps.users",
    "apps.listings",
    "apps.matching",
    "apps.messaging",
    "apps.notifications",
    "apps.bookmarks",
    "apps.core",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# The generated OpenAPI schema. Descriptions live here rather than only in
# docstrings so the published docs read as documentation rather than as leaked
# implementation notes.
SPECTACULAR_SETTINGS = {
    "TITLE": "Neighbour Node API",
    "DESCRIPTION": (
        "Neighbourhood lending: listings, an LLM match agent, bookmarks, "
        "messaging and notifications.\n\n"
        "All endpoints except registration, login and listing reads require "
        "`Authorization: Bearer <access-token>`.\n\n"
        "Two conventions worth knowing before reading further:\n\n"
        "- **Private rows 404, public resources 403.** A bookmark, thread or "
        "notification belonging to someone else is reported as not found, "
        "because confirming it exists is itself a disclosure. A listing you "
        "do not own returns 403 — its existence is not a secret.\n"
        "- **Creates are idempotent** where a double-tap is plausible. "
        "Bookmarking something twice, or opening a conversation that already "
        "exists, returns the existing row with 200 rather than erroring."
    ),
    "VERSION": "1.0.0",
    # The schema endpoint itself is not part of the API being described.
    "SERVE_INCLUDE_SCHEMA": False,
    # Strip the "api" prefix from generated operation ids, so they read
    # listings_list rather than api_listings_list.
    "SCHEMA_PATH_PREFIX": "/api",
    "COMPONENT_SPLIT_REQUEST": True,
    # Serve the Swagger UI assets from the sidecar package via staticfiles rather
    # than the default unpkg.com CDN. Offline-proof, and versioned with the app.
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# SimpleJWT defaults to a 5-minute access token. The frontend keeps it in
# sessionStorage and has no refresh flow yet, so a short life logs the user out
# mid-session.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Per-role LLM provider selection. Each role resolves independently, so Claude
# and DeepSeek can be live at once for different jobs. Values: stub | anthropic | deepseek.
EXTRACTION_PROVIDER = config("EXTRACTION_PROVIDER", default="stub")
MATCHING_PROVIDER = config("MATCHING_PROVIDER", default="stub")

ANTHROPIC_API_KEY = config("ANTHROPIC_API_KEY", default="")
DEEPSEEK_API_KEY = config("DEEPSEEK_API_KEY", default="")


# Only used by the local Vite dev server, which runs on a different port and so
# is genuinely cross-origin. In the container the frontend and the API are both
# behind nginx on one origin, so no preflight ever happens and this list is inert.
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in config("CORS_ALLOWED_ORIGINS", default="http://localhost:5173").split(",")
    if o.strip()
]


AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Directly after SecurityMiddleware and before everything else, per WhiteNoise's
    # docs. With DEBUG=False Django's staticfiles view switches itself off, so
    # without this the admin, the DRF browsable API and /api/docs/ all render as
    # unstyled HTML — the failure looks like a broken app, not a missing setting.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB_PATH lets the container put the file on a mounted volume instead of inside
# the image, where a rebuild would discard it.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": config("DB_PATH", default=str(BASE_DIR / "db.sqlite3")),
        "OPTIONS": {
            # WAL is a property of the *database file*, so one PRAGMA would in
            # principle be enough — but it survives only as long as nobody
            # recreates the file, and the volume gets wiped often enough during
            # setup that "someone forgot to re-run it" is a real failure mode.
            # Issuing it as an init_command makes every new connection assert it,
            # which costs nothing when it's already set.
            #
            # Why it matters here: the default rollback journal takes an exclusive
            # lock for the whole write, so a slow write blocks every reader. WAL
            # lets readers carry on against the last committed snapshot. With one
            # gunicorn worker there is one writer by construction, which is the
            # configuration WAL handles best.
            #
            # busy_timeout is the companion setting people leave out: without it a
            # contended write raises "database is locked" immediately instead of
            # waiting. 5s is far longer than any write here takes.
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            "timeout": 5,
        },
    }
}

# Extraction results are cached on the SHA-256 of the image bytes plus the
# description — see apps/listings/services.py. LocMemCache is per-process and
# dies with the process; Redis is shared and, with a volume behind it, survives a
# container restart. That is the property that matters for a demo: a cache warmed
# the day before is still warm the next morning, so the walkthrough doesn't depend
# on a live vision call going through on the room's wifi.
#
# Falling back to LocMemCache when REDIS_URL is unset keeps a bare `runserver`
# working with no Redis installed.
REDIS_URL = config("REDIS_URL", default="")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Under the test runner only, hash passwords with something fast.
#
# PBKDF2 runs ~600k iterations by design — correct in production, ruinous in a
# suite whose fixtures create three or four users per test. MD5 is safe here
# precisely because nothing under test asserts anything about hash strength;
# tests only need set_password/check_password to round-trip.
#
# Guarded on sys.argv rather than a separate settings module: one settings file
# is easier to keep honest than two that drift.
#
# Matches the SUBCOMMAND position specifically, not `"test" in sys.argv` — the
# looser check would also fire on things like `createsuperuser --username test`
# and silently weaken a real account's password.
RUNNING_TESTS = sys.argv[1:2] == ["test"]
if RUNNING_TESTS:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` writes, and where WhiteNoise reads from. Inside the image
# rather than on a volume — these files are build output, rebuilt from the
# installed packages every time, so there is nothing here worth persisting.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    # Uploaded photos. Plain filesystem storage, pointed at the media volume.
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # Hashes each file's contents into its name and writes a manifest, so
    # collected assets can be served with a far-future cache header and still
    # change the instant a deploy does. The compression step pre-builds gzip and
    # brotli copies at build time rather than per request.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "/media/"
# On a volume, unlike STATIC_ROOT: these are uploads, and the only copy is the one
# on disk. Baked into the image they would be discarded by every rebuild, and the
# seeded listings would point at photos that no longer exist.
MEDIA_ROOT = Path(config("MEDIA_ROOT", default=str(BASE_DIR / "media")))
