"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)


ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "apps.users",
    "apps.listings",
    "apps.matching",
    "apps.messaging",
    "apps.notifications",
    "apps.bookmarks",
    "apps.core",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# The generated OpenAPI schema. Descriptions live here rather than only in
# docstrings so the published docs read as documentation rather than as leaked
# implementation notes.
SPECTACULAR_SETTINGS = {
    "TITLE": "Neighbour Node API",
    "DESCRIPTION": (
        "Neighbourhood lending: listings, an LLM match agent, bookmarks, "
        "messaging and notifications.\n\n"
        "All endpoints except registration, login and listing reads require "
        "`Authorization: Bearer <access-token>`.\n\n"
        "Two conventions worth knowing before reading further:\n\n"
        "- **Private rows 404, public resources 403.** A bookmark, thread or "
        "notification belonging to someone else is reported as not found, "
        "because confirming it exists is itself a disclosure. A listing you "
        "do not own returns 403 — its existence is not a secret.\n"
        "- **Creates are idempotent** where a double-tap is plausible. "
        "Bookmarking something twice, or opening a conversation that already "
        "exists, returns the existing row with 200 rather than erroring."
    ),
    "VERSION": "1.0.0",
    # The schema endpoint itself is not part of the API being described.
    "SERVE_INCLUDE_SCHEMA": False,
    # Strip the "api" prefix from generated operation ids, so they read
    # listings_list rather than api_listings_list.
    "SCHEMA_PATH_PREFIX": "/api",
    "COMPONENT_SPLIT_REQUEST": True,
}

# SimpleJWT defaults to a 5-minute access token. The frontend holds it in memory
# and has no refresh flow yet, so a short life logs the user out mid-session.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# Per-role LLM provider selection. Each role resolves independently, so Claude
# and DeepSeek can be live at once for different jobs. Values: stub | anthropic | deepseek.
EXTRACTION_PROVIDER = config("EXTRACTION_PROVIDER", default="stub")
MATCHING_PROVIDER = config("MATCHING_PROVIDER", default="stub")

ANTHROPIC_API_KEY = config("ANTHROPIC_API_KEY", default="")
DEEPSEEK_API_KEY = config("DEEPSEEK_API_KEY", default="")


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]


AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Under the test runner only, hash passwords with something fast.
#
# PBKDF2 runs ~600k iterations by design — correct in production, ruinous in a
# suite whose fixtures create three or four users per test. MD5 is safe here
# precisely because nothing under test asserts anything about hash strength;
# tests only need set_password/check_password to round-trip.
#
# Guarded on sys.argv rather than a separate settings module: one settings file
# is easier to keep honest than two that drift.
#
# Matches the SUBCOMMAND position specifically, not `"test" in sys.argv` — the
# looser check would also fire on things like `createsuperuser --username test`
# and silently weaken a real account's password.
RUNNING_TESTS = sys.argv[1:2] == ["test"]
if RUNNING_TESTS:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
