# Generated by Django 6.0.7 on 2026-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="listings/%Y/%m/"),
        ),
    ]
