# Generated by Django 6.0.7 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tracelog",
            options={"ordering": ["run_id", "step_index", "created_at"]},
        ),
        migrations.AddField(
            model_name="tracelog",
            name="duration_ms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tracelog",
            name="run_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="tracelog",
            name="status",
            field=models.CharField(default="ok", max_length=20),
        ),
        migrations.AddField(
            model_name="tracelog",
            name="step_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tracelog",
            name="tool_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
